export const conf = {
    firebaseurl: String(import.meta.env.VITE_FIREBASE_ENDPOINT || "https://cloud.firebase.io/v1").trim(),
    firebaseProjectId: String(import.meta.env.VITE_FIREBASE_PROJECT_ID || "vakrayan-9ce25").trim(),
    firebaseDatabaseId: String(import.meta.env.VITE_FIREBASE_DATABASE_ID || "vakrayan-9ce25").trim(),
    firebaseProductsCollectionId: String(import.meta.env.VITE_FIREBASE_PRODUCTS_COLLECTION_ID || "products").trim(),
    firebaseCartCollectionId: String(import.meta.env.VITE_FIREBASE_CART_COLLECTION_ID || "cart").trim(),
    firebaseOrdersCollectionId: String(import.meta.env.VITE_FIREBASE_ORDERS_COLLECTION_ID || "orders").trim(),
    firebaseCouponsCollectionId: String(import.meta.env.VITE_FIREBASE_COUPONS_COLLECTION_ID || "coupons").trim(),
    firebaseCampaignsCollectionId: String(import.meta.env.VITE_FIREBASE_CAMPAIGNS_COLLECTION_ID || "newsletter").trim(),
    firebaseAddressesCollectionId: String(import.meta.env.VITE_FIREBASE_ADDRESSES_COLLECTION_ID || "addresses").trim(),
    firebaseReviewsCollectionId: String(import.meta.env.VITE_FIREBASE_REVIEWS_COLLECTION_ID || "reviews").trim(),
    firebaseSettingsCollectionId: String(import.meta.env.VITE_FIREBASE_SETTINGS_COLLECTION_ID || "settings").trim(),
    firebaseWishlistCollectionId: String(import.meta.env.VITE_FIREBASE_WISHLIST_COLLECTION_ID || "wishlist").trim(),
    firebaseCouponUsageCollectionId: String(import.meta.env.VITE_FIREBASE_COUPON_USAGE_COLLECTION_ID || "coupon_usage").trim(),
    firebaseRestockCollectionId: String(import.meta.env.VITE_FIREBASE_RESTOCK_COLLECTION_ID || "restock_notifications").trim(),
    firebaseSlidesCollectionId: String(import.meta.env.VITE_FIREBASE_SLIDES_COLLECTION_ID || "slides").trim(),
    firebaseOffersCollectionId: String(import.meta.env.VITE_FIREBASE_OFFERS_COLLECTION_ID || "offers").trim(),
    firebaseWalletCollectionId: String(import.meta.env.VITE_FIREBASE_WALLET_COLLECTION_ID || "wallet").trim(),
    firebaseCategoryConfigsCollectionId: String(import.meta.env.VITE_FIREBASE_CATEGORY_CONFIGS_COLLECTION_ID || "category_configs").trim(),
    firebaseBucketId: String(import.meta.env.VITE_FIREBASE_BUCKET_ID || "images").trim(),
    firebaseCloudflareWorkerUrl: String(import.meta.env.VITE_CLOUDFLARE_WORKER_URL || "https://b2-upload-gateway.vakrayan.workers.dev/").trim(),
}